server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver



#pagehelper:
#  auto-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  page-size-zero: true
#  params: count=countSql